import React, { useEffect, useState } from "react";
import { CheckCircle2, Shield, Brain, AlertCircle } from "lucide-react";

/**
 * Receipts — proof-points auto-generated from /stats.json.
 *
 * The JSON is produced by scripts/generate_stats.py which runs the same
 * pattern corpus the test suite asserts on. So every number rendered
 * here is tied to a green pytest run — "claims" become "receipts".
 *
 * Falls back silently if stats.json is missing so a fresh checkout
 * without a CI run doesn't render a broken panel.
 */
export default function Receipts() {
  const [stats, setStats] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    const base = process.env.PUBLIC_URL || "";
    fetch(`${base}/stats.json`, { cache: "no-cache" })
      .then((r) => {
        if (!r.ok) throw new Error(`status ${r.status}`);
        return r.json();
      })
      .then(setStats)
      .catch((e) => setError(String(e)));
  }, []);

  if (error || !stats) return null;

  const generated = stats.generated_at
    ? new Date(stats.generated_at).toISOString().slice(0, 10)
    : "—";

  const items = [
    {
      icon: <CheckCircle2 size={22} className="text-emerald-400" />,
      metric: `${(stats.detection_rate * 100).toFixed(1)}%`,
      label: "detection rate",
      sub: `${stats.synthetic_secrets_tested} synthetic API keys, JWTs, PEMs, DB URLs`,
      testid: "receipt-detection-rate",
    },
    {
      icon: <Shield size={22} className="text-emerald-400" />,
      metric: `${(stats.false_positive_rate * 100).toFixed(2)}%`,
      label: "false-positive rate",
      sub: `${stats.false_positives_tested} code, docs & config samples audited`,
      testid: "receipt-fp-rate",
    },
    {
      icon: <Brain size={22} className="text-amber-400" />,
      metric: `${stats.patterns_active}`,
      label: "patterns + ML entropy",
      sub: stats.ml_entropy_enabled
        ? "Shannon entropy × variety × length × pattern boost"
        : "regex patterns active",
      testid: "receipt-patterns",
    },
  ];

  return (
    <section
      id="receipts"
      data-testid="receipts-section"
      className="relative border-b border-white/10 bg-[#0A0A0A]"
    >
      <div className="max-w-7xl mx-auto px-6 md:px-10 py-14 md:py-20">
        <div className="flex items-baseline justify-between gap-6 mb-8 flex-wrap">
          <div>
            <div className="font-mono text-[11px] tracking-[0.18em] text-amber-400 mb-2">
              ▍ RECEIPTS, NOT CLAIMS
            </div>
            <h2
              style={{ fontFamily: "Cabinet Grotesk, sans-serif" }}
              className="text-3xl md:text-5xl font-extrabold tracking-tight text-white"
              data-testid="receipts-headline"
            >
              Measured on every build.
            </h2>
          </div>
          <div className="font-mono text-[11px] text-zinc-500" data-testid="receipts-timestamp">
            generated {generated} · <span className="text-zinc-400">stats.json</span> ·{" "}
            <span className="text-zinc-400">v{stats.version}</span>
          </div>
        </div>

        <div className="grid md:grid-cols-3 gap-px bg-white/10 border border-white/10">
          {items.map((it) => (
            <div
              key={it.label}
              data-testid={it.testid}
              className="bg-[#0A0A0A] p-7 md:p-9 flex flex-col gap-4 hover:bg-white/[0.02] transition-colors"
            >
              <div className="flex items-center gap-2">
                {it.icon}
                <span className="font-mono text-[10px] tracking-[0.16em] text-zinc-500 uppercase">
                  {it.label}
                </span>
              </div>
              <div
                style={{ fontFamily: "Cabinet Grotesk, sans-serif" }}
                className="text-5xl md:text-6xl font-extrabold tracking-tight text-white leading-none"
              >
                {it.metric}
              </div>
              <div className="text-sm text-zinc-400 leading-snug">{it.sub}</div>
            </div>
          ))}
        </div>

        <div className="mt-6 flex items-center gap-2 font-mono text-[11px] text-zinc-500">
          <AlertCircle size={12} />
          <span>
            Numbers regenerated by <code className="text-zinc-400">scripts/generate_stats.py</code>{" "}
            — tied to the green pytest corpus (<code className="text-zinc-400">backend/tests/test_corpus.py</code>).
          </span>
        </div>
      </div>
    </section>
  );
}
