"""
Vibe Protect — responsible-disclosure evidence bundler.

Does NOT auto-submit anywhere. Generates a Markdown report the researcher
can paste into Huntr / a GitHub Security Advisory / an email, pre-filled
with non-PII environment context.

Nothing in here makes a network call.
"""

from __future__ import annotations

import platform
import sys
import textwrap
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional


def _version() -> str:
    v = Path(__file__).resolve().parent.parent / "VERSION"
    if v.exists():
        return v.read_text().strip()
    return "unknown"


def _pattern_count() -> int:
    try:
        sys.path.insert(0, str(Path(__file__).resolve().parent))
        from patterns import PATTERNS  # type: ignore
        return len(PATTERNS)
    except Exception:
        return -1


def generate_report(
    title: str = "",
    description: str = "",
    severity: str = "medium",
    poc: str = "",
    include_audit_dir: bool = False,
) -> str:
    """Return a Markdown disclosure report. Never includes secret content."""
    tmpl = textwrap.dedent(f"""
    # Vibe Protect — vulnerability report

    **Please submit this via one of:**
    - Huntr: https://huntr.dev/bounties/disclose/?target=https%3A%2F%2Fgithub.com%2Fvibeprotect%2Fvibe-protect
    - GitHub Security Advisory (private): https://github.com/vibeprotect/vibe-protect/security/advisories/new

    ## Summary
    **Title:** {title or "(please fill in)"}

    **Severity:** {severity}

    **Reported:** {datetime.now(timezone.utc).isoformat()}

    ## Environment (auto-collected — no PII)
    | | |
    | --- | --- |
    | Vibe Protect version | {_version()} |
    | Python               | {platform.python_version()} |
    | OS                   | {platform.system()} {platform.release()} |
    | Architecture         | {platform.machine()} |
    | Bundled patterns     | {_pattern_count()} |
    | Audit dir included   | {include_audit_dir} |

    ## Description
    {description or "_Describe what you observed, what you expected, and the impact._"}

    ## Reproduction

    ```
    {poc or "# steps to reproduce or minimal failing input"}
    ```

    ## Impact assessment
    _What can an attacker do with this bug? Who is affected? Under what
    preconditions?_

    ## Suggested fix (optional)
    _If you have one — PRs welcome too._

    ---

    *Generated by `python vibe_protect.py --report-vuln`. Contains no
    clipboard content, no file contents, no IP or username.*
    """).strip()
    return tmpl + "\n"


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser(
        description="Generate a responsible-disclosure evidence bundle (no network calls)"
    )
    ap.add_argument("--title", default="")
    ap.add_argument("--severity", choices=["critical", "high", "medium", "low"], default="medium")
    ap.add_argument("--description", default="")
    ap.add_argument("--poc", default="")
    ap.add_argument("--out", help="write the report to this path instead of stdout")
    args = ap.parse_args()

    md = generate_report(
        title=args.title,
        description=args.description,
        severity=args.severity,
        poc=args.poc,
    )
    if args.out:
        Path(args.out).write_text(md)
        print(f"✓ report written to {args.out}")
    else:
        print(md)
